Algoritmo "Exercício 3"

Var
      a,b,c,somaValores: real
Inicio
      escreval("Entre com o primeiro número")
      leia(a)
      
      escreval("Entre com o segundo número")
      leia(b)
      
      escreval("Entre com o terceiro número")
      leia(c)
      
      somaValores <- 0
      somaValores <- exp(a,2)+exp(b,2)+exp(c,2)
      
      escreva("A soma dos valores ao quadrado é:",somaValores)
Fimalgoritmo
