Algoritmo "Exercício 4"

Var
    a,b,c,vlFinal: inteiro
Inicio
      escreval("Entre com o valor A")
      leia(a)
      
      escreval("Entre com o valor B")
      leia(b)
      
      escreval("Entre com o valor C")
      leia(c)
      
      vlFinal <- 0
      vlFinal <- quad(a+b+c)
      
      escreva("O quadrado da soma dos valores é:",vlFinal)
      
      
Fimalgoritmo